# Generated by Django 2.0 on 2018-07-06 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('empid', models.TextField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('Salary', models.BigIntegerField()),
                ('dob', models.TextField(max_length=100)),
            ],
        ),
    ]
