# Generated by Django 2.0 on 2018-07-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='empid',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
